# Generated by Django 4.1.7 on 2023-02-16 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('surname', models.CharField(default='', max_length=30)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=5)),
                ('password', models.CharField(default='12345678', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default=None)),
                ('gender', models.CharField(default='', max_length=5)),
                ('position', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='12345678', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('wid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('publisher', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('bid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('sellDate', models.DateField(default=None)),
                ('picture', models.ImageField(default='', upload_to='static/ebook/')),
                ('desc', models.TextField(default='', max_length=5000)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.category')),
                ('writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.writer')),
            ],
        ),
    ]
