# Generated by Django 4.1.7 on 2023-02-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0002_remove_category_desc_category_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=1)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprice', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('ebook', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.ebook')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
    ]
