# Generated by Django 4.1.7 on 2023-02-24 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0003_rename_employees_employee_remove_customers_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.CreateModel(
            name='Samplesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesale', models.DateField(default=None)),
                ('amount', models.IntegerField(default=0)),
                ('ebook', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.ebook')),
            ],
        ),
        migrations.CreateModel(
            name='Confirms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.employee')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Accepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.employee')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
    ]
