# Generated by Django 4.1.7 on 2023-02-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0004_remove_employee_birthdate_remove_employee_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='odate',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='gender',
        ),
    ]
