# Generated by Django 4.1.7 on 2023-02-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0005_rename_date_orders_odate_remove_customers_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesale',
            name='ebook',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Samplesale',
        ),
    ]
