# Generated by Django 4.1.7 on 2023-02-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0006_remove_samplesale_ebook_delete_orderdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samplesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesale', models.DateField(default=None)),
                ('amount', models.IntegerField(default=0)),
                ('ebook', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.ebook')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprice', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('ebooks', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.ebook')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
    ]
