# Generated by Django 4.1.7 on 2023-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0007_samplesale_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='net',
            field=models.IntegerField(default=0),
        ),
    ]
