# Generated by Django 4.1.7 on 2023-02-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0008_ebook_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(default='', max_length=35)),
                ('bank', models.CharField(default='', max_length=50)),
                ('bill', models.ImageField(default='', upload_to='static/bills/')),
                ('comment', models.CharField(default='', max_length=200)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(default='', max_length=50)),
                ('tag', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.employee')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.employee')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=200)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EbookApp.orders')),
            ],
        ),
    ]
